actions:
  - type: remove
    selector: ".ad-banner"
    priority: 1
  - type: replace
    selector: "#main-header"
    newElement: "<header id='new-header'><h1>Welcome to My Updated Website</h1></header>"
    priority: 2
