actions:
  - type: insert
    position: "after"
    target: "nav"
    element: "<section><h2>Latest News</h2><p>Stay updated with the latest news here.</p></section>"
    priority: 1
  - type: alter
    oldValue: "technology"
    newValue: "innovation"
    priority: 2
